//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroVets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veterinario_Especialidad
    {
        public int Veterinario_Especialidad_Id { get; set; }
        public int Veterinario_Id { get; set; }
        public int Especialidad_Id { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
    }
}
