//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MicroCreditos.Models
{
    public partial class Mascota
    {
        public int Mascota_Id { get; set; }
        public string Mascota1 { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public int Tipo_Id { get; set; }
        public int Dueno_Id { get; set; }

        public virtual Tipo Tipo { get; set; }
        public virtual Dueno Dueno { get; set; }
    }
}
